import Head from "next/head";
import { useEffect, useState } from "react";
import Link from 'next/link';
bootstrap


export default function Home() {
const [searchInput,setSearchInput] = useState('');
  const accessToken = "BQBBzatcwkDRKgoIMZ3SBTS-YRx-wDBDt-qHTEY6vHUNDmzpCrK1-dliRX";
const client_id = '017de660e7444fa7a690fd422b198f9f'; // Your client id

fetch(`https://api.spotify.com/v1/albums/017de660e7444fa7a690fd422b198f9f`, {
  headers: {
    Authorization: `Bearer ${accessToken}`,
  },
})
  .then((response) => response.json())
  .then((Response) => thisistest(Response))
  .then((data) => {
    console.log(data);
  })
  .catch((error) => {
    console.error("Error fetching playlists:", error);
  });
  function thisistest(aa){
    console.log(aa)

  }
  console.log(searchInput ,'인풋창 변경 확인')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>
        <div id="login">
          <h1>First, log in to spotify</h1>
          <Link href="/comp/login">Log in</Link>
        </div>
        <div id="loggedin"></div>
      </div>
      {
        useEffect(()=>{
          <script id="loggedin-template" type="text/x-handlebars-template">
          <h1>Logged in as </h1>
          <img id="avatar" width="200" src="" />
          <dl>
            <dt>Display name</dt>
            <dd></dd>
            <dt>Username</dt>
            <dd></dd>
            <dt>Email</dt>
            <dd></dd>
            <dt>Spotify URI</dt>
            <dd>
              <Link href=""></Link>
            </dd>
            <dt>Link</dt>
            <dd>
              <Link href=""></Link>
            </dd>
            <dt>Profile Image</dt>
            <dd></dd>
          </dl>
          <p>
            <Link href="/">Log in again</Link>
          </p>
        </script>
        },[])
      } */}


      <input placeholder='search for artist' type="input" onKeyPress={e=>{
        if(e.key == "Enter"){
          console.log('엔터키' + searchInput)
        }
      }}
      onChange={e=> setSearchInput(e.target.value)}
      ></input>
      <button onClick={e=>{console.log('버튼클릭' + searchInput)}}>검색</button>
    </>
  );
}
