import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios'
import { translateText } from './api/hello'
import text from './comp/text'
import { useEffect, useState } from 'react'



export default function Home() {

    const [inputText, setInputText] = useState('');
    const [translatedText, setTranslatedText] = useState('');
  
    async function handleTranslate() {
      const result = await translateText(inputText);
      setTranslatedText(result);
    }
    console.log(inputText,'인풋창')

     

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <input value={inputText} onChange={(e) => setInputText(e.target.value)} />
      <button onClick={handleTranslate}>Translate</button>
      {translatedText && <p>{translatedText}</p>}
    </div>
    </>
  )
}
